version: "3.9"

services:
  kdv-telegram-bot:
    build: .
    container_name: kdv-telegram-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./users.json:/app/users.json
      - ./static:/app/static
    # Если нужно логировать в консоль
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
